### ISSUE TITLE
Interface Proposal

### ISSUE THREAD

**Issue by sraleigh62** [cs-worcester-cs-448-sp-2019/Theas-Pantry#1]
As developers, we need to come up with a proposal to present our interface to our customers.

**Comment by kwurst** [comment]
@sraleigh62  This should be an issue on https://github.com/LibreFoodPantry/Theas-Pantry

Please create this issue on that repository, then close it here with a comment explaining why it was closed and a link to the new issue.

**Comment by sraleigh62** [comment]
Closed this issue as it was moved to the Theas-Pantry repository located here: https://github.com/LibreFoodPantry/Theas-Pantry/issues/8
