### ISSUE TITLE
Add documentation/comments to REST API.

### ISSUE THREAD

**Issue by irresoluteduck** [cs-worcester-cs-448-sp-2019/Theas-Pantry#10]

**Comment by kwurst** [comment]
@irresoluteduck  This should be an issue on https://github.com/LibreFoodPantry/FoodKeeper-API

Please create this issue on that repository, then close it here with a comment explaining why it was closed and a link to the new issue.

**Comment by irresoluteduck** [comment]
Issue incorrectly placed in wrong repository, link to new issue in correct repository:
https://github.com/cs-worcester-cs-448-sp-2019/FoodKeeper-API/issues/5
