### ISSUE TITLE
Update README with appropriate information related to this project.

### ISSUE THREAD

**Issue by irresoluteduck** [cs-worcester-cs-448-sp-2019/Theas-Pantry#11]
Information regarding dependencies and other angular related services should be included if getting started is unclear.

**Comment by kwurst** [comment]
@irresoluteduck This should be an issue on https://github.com/LibreFoodPantry/FoodKeeper-API

**Comment by irresoluteduck** [comment]
Corrected the title to better reflect this project and updated description.
