### ISSUE TITLE
Feature: Filter by Category: Dairy, Poultry, Vegetables, etc.

### ISSUE THREAD

**Issue by banderson8** [cs-worcester-cs-448-sp-2019/Theas-Pantry#12]

**Comment by kwurst** [comment]
@banderson8 This should be an issue for https://github.com/LibreFoodPantry/FoodKeeper-API

**Comment by irresoluteduck** [comment]
Issue incorrectly placed in wrong repository, link to new issue in correct repository:
https://github.com/cs-worcester-cs-448-sp-2019/FoodKeeper-API/issues/6
