### ISSUE TITLE
Create Landing Page for Food Keeper Rest API

### ISSUE THREAD

**Issue by banderson8** [cs-worcester-cs-448-sp-2019/Theas-Pantry#16]

**Comment by kwurst** [comment]
This should be an issue on https://github.com/LibreFoodPantry/FoodKeeper-API

**Comment by irresoluteduck** [comment]
Issue incorrectly placed in wrong repository, link to new issue in correct repository:
https://github.com/cs-worcester-cs-448-sp-2019/FoodKeeper-API/issues/7
