### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by jfarrar1** [cs-worcester-cs-448-sp-2019/Theas-Pantry#2]
As developers on this team, we need to establish connection with our project to Heroku.

**Comment by kwurst** [comment]
@jfarrar1 This should be an issue on https://github.com/LibreFoodPantry/FoodKeeper-API

Please create this issue on that repository, then close it here with a comment explaining why it was closed and a link to the new issue.

**Comment by jfarrar1** [comment]
We were thinking of using Heroku for both Thea's Pantry and the FoodKeeper API, but this issue does not belong here so I moved them to their respective repositories. 

FoodKeeper: https://github.com/LibreFoodPantry/FoodKeeper-API/issues/9
Thea's Pantry: https://github.com/LibreFoodPantry/Theas-Pantry/issues/3
