### ISSUE TITLE
OneCard Scanning IDs

### ISSUE THREAD

**Issue by sburke4747** [cs-worcester-cs-448-sp-2019/Theas-Pantry#27]
As a Food Pantry worker, I'd like to be able to scan a customer's OneCard so I do not have to manually type the ID number.

**Comment by kwurst** [comment]
This issue should be on https://github.com/LibreFoodPantry/Theas-Pantry

**Comment by sburke4747** [comment]
This issue has been replaced with the following story on the LibreFoodPantry repository. 

https://github.com/LibreFoodPantry/Theas-Pantry/issues/10
