### ISSUE TITLE
OneCard Scanning

### ISSUE THREAD

**Issue by jfarrar1** [cs-worcester-cs-448-sp-2019/Theas-Pantry#3]
As developers, we need to get a better understanding of how the OneCard ID#'s are scanning into Google Forms/Sheets.

**Comment by kwurst** [comment]
@jfarrar1 This should be an issue on https://github.com/LibreFoodPantry/FoodKeeper-API

Please create this issue on that repository, then close it here with a comment explaining why it was closed and a link to the new issue.

**Comment by rvillegas1** [comment]
Shouldn't this be on [https://github.com/LibreFoodPantry/Theas-Pantry](url) ?

**Comment by jfarrar1** [comment]
This is an issue for Thea's Pantry. It seems like it has already been moved to: https://github.com/LibreFoodPantry/Theas-Pantry/issues/4
