### ISSUE TITLE
Intake Form: Household Size

### ISSUE THREAD

**Issue by sburke4747** [cs-worcester-cs-448-sp-2019/Theas-Pantry#38]
Food pantry workers will need to know the household size for each customer regardless of how many people are physically visiting the pantry. If a student is using their on-campus address, this number should always be 1.

This also means one household per ID number.

This information is relevant to [Story#6](https://github.com/LibreFoodPantry/Theas-Pantry/issues/6).

**Comment by irresoluteduck** [comment]
Closed, already on the intake form.

**Comment by sburke4747** [comment]
Reopening this issue based on a need for this specific field for WCFB reports form. This is somewhat answered on the existing form, but a specific field for this will be necessary.
