### ISSUE TITLE
Intake Form: Ages of Household Members

### ISSUE THREAD

**Issue by sburke4747** [cs-worcester-cs-448-sp-2019/Theas-Pantry#39]
Food pantry workers will also need to know the ages of every household member, including the customer who is visiting the pantry.

This is based on [Story#6](https://github.com/LibreFoodPantry/Theas-Pantry/issues/6).

Age groups are as follows:
    * 0-4
    * 5-17
    * 18-64
    * 65-UP

**Comment by irresoluteduck** [comment]
Age groups need to be modified, age ranges are too broad.

**Comment by sburke4747** [comment]
These age groups were given by the county food bank. We can set a "max" age but otherwise this is what the Worcester County Food Bank is requiring for their reports.

**Comment by irresoluteduck** [comment]
@sburke4747 Okay, understood. Will relay the information to the appropriate channels.
