### ISSUE TITLE
Intake Form: Add optional field for gender.

### ISSUE THREAD

**Issue by irresoluteduck** [cs-worcester-cs-448-sp-2019/Theas-Pantry#41]
Food pantry workers will need to ask new customers for their gender but an answer is optional not required.

**Comment by sburke4747** [comment]
Please note that these fields cannot be mandatory. I spoke with Bridget Joiner from the Student Affairs office about this and we cannot force people to answer this question.

**Comment by irresoluteduck** [comment]
@sburke4747 Okay, understood. Will relay this information to the appropriate channels.

**Comment by irresoluteduck** [comment]
Added specification to allow for optional completion of field.
