### ISSUE TITLE
Intake Form: Add Field for Annual Income

### ISSUE THREAD

**Issue by jfarrar1** [cs-worcester-cs-448-sp-2019/Theas-Pantry#44]
Food pantry workers will need to know the annual household income for future reports. This can be done by asking if the applicant's annual income exceeds an amount based on the number of household members.

**Comment by sburke4747** [comment]
This will be an adjustment to the existing alphabetical drop down that exists on the form as of right now. The income number is based off of ranges on the existing form that the food pantry is using.
<img width="508" alt="IncomeBasedOnHouseholdNumbers" src="https://user-images.githubusercontent.com/26254758/56334382-0fbb4380-6166-11e9-9e71-e59cf855a739.png">

**Comment by jfarrar1** [comment]
Issue has been completed and merged with the master branch
