### ISSUE TITLE
Update Intake Form

### ISSUE THREAD

**Issue by hivunhat** [cs-worcester-cs-448-sp-2019/Theas-Pantry#5]
As developer, we want to update the Pantry Intake Form base on WCFB DATA COLLECTION SYSTEM. The form they have now missing important information as zip code, number of people in household, ages served and primary household income source.
I create mock google form we can base on: [https://docs.google.com/forms/d/e/1FAIpQLScDr3CdhB9G-6Ek92UPWDUSBOj2ZLHLo3uusPyEc5VgbcrA-w/viewform](url)

**Comment by sraleigh62** [comment]
We can use this intake form as a basis to create new forms / load forms for issue #4 ?

**Comment by hivunhat** [comment]
Yes but I don't fully understand what are they looking for specialty in the income session, so I will keep update it and think about how we manage the data.

**Comment by kwurst** [comment]
@hivunhat  This should be an issue on https://github.com/LibreFoodPantry/Theas-Pantry

Please create this issue on that repository, then close it here with a comment explaining why it was closed and a link to the new issue.

**Comment by hivunhat** [comment]
Replace this issue to [Task - Update Intake Form #5](https://github.com/LibreFoodPantry/Theas-Pantry/issues/5)
