### ISSUE TITLE
MongoDB as database

### ISSUE THREAD

**Issue by hivunhat** [cs-worcester-cs-448-sp-2019/Theas-Pantry#6]
As developer, we are using Heroku. We use MongoDB for better storing data.

**Comment by kwurst** [comment]
@hivunhat Is this for Thea's Pantry or the FoodKeeper-API?

Was there a decision made to use Heroku and MongoDB for Thea's Pantry?

**Comment by sburke4747** [comment]
Replaced with the following issue on the other repo...
https://github.com/LibreFoodPantry/Theas-Pantry/issues/2

**Comment by hivunhat** [comment]
Close issue because replace by [https://github.com/LibreFoodPantry/Theas-Pantry/issues/2](url)
